site_name: Prueba_NLP

site_author: Pablo Sanchez Cabrera
repo_url: 
use_directory_urls: false

nav:
  - Home:
      - Welcome to NLP Project: start/README.md
  - API Reference:
      - Descriptive:
          - Graphs: modules/descriptive/graphs.md
      - Preprocessing:
          - Text: modules/preprocessing/preprocessing.md
      - Model:
          - Sentiment Analysis & Topic Prediction: modules/model/model.md
  - User Guide:
      - Project: user_guides/User-Guide.ipynb

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          selection:
            inherited_member: true
            new_path_syntax: false
            docstring_style: numpy
            merge_init_into_class: yes
            separate_signature: yes
            filters:
              - "!^_"  # exclude all members starting with _
          rendering:
            show_root_heading: yes
            docstring_section_style: table

  - mkdocs-jupyter:
      include_source: False
      ignore_h1_titles: True
      include_source: True

  - search

theme:
    name: mkdocs
    locale: en
    include_sidebar: false

markdown_extensions:
    - toc:
        permalink: "#"
        baselevel: 2
        separator: "_"